name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    name: Jekyll Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: TailwindCSS Build
        run: npm run build
      - name: Jekyll Build
        run: bundle exec jekyll build
      - name: minify HTML
        run: |
          wget -O minhtml -q https://github.com/wilsonzlin/minify-html/releases/download/v0.16.4/minhtml-0.16.4-x86_64-unknown-linux-gnu &&
            chmod +x minhtml &&
            ./minhtml _site/**/*.html _site/*.html
