name: GitHub Pages
on:
  push:
    branches:
      - main
env:
  TZ: 'Asia/Tokyo'
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock')}}
        restore-keys: ${{ runner.os }}-bundler-
    - name: bundle install
      run: |
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Jekyll Build
      run: bundle exec jekyll build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
